site_name: "Retrofit2 Synchronous Adapter"
site_url: https://jaredsburrows.github.io/retrofit2-synchronous-adapter
repo_name: retrofit2-synchronous-adapter
repo_url: https://github.com/jaredsburrows/retrofit2-synchronous-adapter
site_description: "Retrofit2 Synchronous Adapter"
site_author: Jared Burrows
remote_branch: gh-pages
edit_uri: ""

copyright: 'Copyright &copy; 2024 Jared Burrows'

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/sun-24
        name: "Switch to Dark Mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/moon-24
        name: "Switch to Light Mode"
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

nav:
  - 'Overview':
    - 'Overview': index.md
  - 'API': javadoc/
  - 'Change Log':
      - 'Change Log': changelog.md
