name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew --version

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.4.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew --version

      - name: Run Build and Unit Tests
        run: ./gradlew build -s

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          comment_mode: off
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        if: github.repository == 'jaredsburrows/retrofit2-synchronous-adapter' && github.ref == 'refs/heads/master'
        with:
          name: retrofit2-synchronous-adapter-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/libs
            build/outputs
            build/publications
            build/distributions
            build/reports
            build/test-results

  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    if: github.repository == 'jaredsburrows/retrofit2-synchronous-adapter' && github.ref == 'refs/heads/master'
    needs:
      - build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew --version

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.4.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.2

      - name: Publish
        run: ./gradlew publish -s
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: retrofit2-synchronous-adapter/build/docs/javadoc
          destination_dir: docs/0.x/
          user_name: "Github Actions"
          user_email: "action@github.com"
