name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.1

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.0
        with:
          gradle-home-cache-cleanup: true

      - name: Run Build
        run: ./gradlew build -s

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2.10.0
        if: always()
        with:
          comment_mode: off
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        if: github.repository == 'jaredsburrows/retrofit2-synchronous-adapter' && github.ref == 'refs/heads/master'
        with:
          name: retrofit2-synchronous-adapter-${{ github.workflow }}-${{ github.run_id }}
          path: |
            build/libs
            build/outputs
            build/publications
            build/distributions
            build/reports
            build/test-results
